[build]
  publish = "build/web"
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"

[build.environment]
  FLUTTER_VERSION = "3.7.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
