[build]
  command = "([ -d flutter ] || git clone https://github.com/flutter/flutter.git -b stable --depth 1) && ./flutter/bin/flutter config --enable-web && mkdir -p assets && echo \"SUPABASE_URL=$SUPABASE_URL\" > assets/env && echo \"SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY\" >> assets/env && ./flutter/bin/flutter build web --release --no-tree-shake-icons"
  publish = "build/web"

[build.environment]
  FLUTTER_CHANNEL = "stable"
