[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 && ./flutter/bin/flutter config --enable-web && echo \"SUPABASE_URL=\$SUPABASE_URL\" > .env && echo \"SUPABASE_ANON_KEY=\$SUPABASE_ANON_KEY\" >> .env && ./flutter/bin/flutter build web --release --no-tree-shake-icons"
  publish = "build/web"

[build.environment]
  FLUTTER_CHANNEL = "stable"
